name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: |
          pip install pytest flake8

      - name: Rodar testes
        run: |
          pytest

      - name: Análise estática com flake8
        run: |
          flake8 garrafas.py